server:
  port: 9090

spring:
  application:
    name: movie-service

log-analysis-service:
  url: http://localhost:9079

logging:
  file:
    name: logs/movie-service.log

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"
