spring:
  application:
    name: agent

server:
  port: 8083

#logging:
#   config: classpath:log4j2.xml
#   file:
#     name: /var/log/service/agent.log
#
#  level:
#    root: DEBUG
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
