spring:
  application:
    name: agent

logging:
   config: classpath:log4j2-spring.xml
#logging:
#  file:
#    name: logs/agent.log
#
#  level:
#    root: DEBUG
#
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"